spring:
  application:
    name: oidc-lab
  datasource:
    url: jdbc:h2:mem:testdb  # Use in-memory database
    driverClassName: org.h2.Driver
    username: sa
    password:
    jpa:
      hibernate:
        ddl-auto: update
      database-platform: org.hibernate.dialect.H2Dialect
    h2:
      console:
        enabled: true
        path: /h2-console
    hikari:
      housekeeping:
        periodMs=60000:
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 587
    username: fa55414443a4f6
    password: f8dd0b5a2439c3
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
